name: Build and Deploy Cloud Run Application

on:
  push:
    branches:
      - main
    paths:
      - 'cloudrun/app/**'

env:
  GCP_PROJECT_ID: int-001
  GCP_REGION: us-west1
  # Matches the ID defined in your terraform main.tf
  AR_REPO_NAME: dbt-docker-repo 
  # Matches the service name defined in your terraform main.tf
  CLOUD_RUN_SERVICE_NAME: dbt-job-runner-service
  IMAGE_TAG: latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # Required for OIDC authentication
      id-token: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Authenticate using Workload Identity Federation (WIF) - requires WIF setup in terraform/wif module
      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@v2
        with:
          # Use the Service Account email created by your service_accounts module
          service_account: github-actions-sa@int-001.iam.gserviceaccount.com 
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure Docker to use Artifact Registry
        run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev

      - name: Build and push Docker image
        id: build-image
        run: |
          IMAGE_URI=${{ env.GGCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.AR_REPO_NAME }}/dbt-runner:${{ env.IMAGE_TAG }}
          docker build ./cloudrun/app --tag $IMAGE_URI
          docker push $IMAGE_URI
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_OUTPUT

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.CLOUD_RUN_SERVICE_NAME }}
          region: ${{ env.GCP_REGION }}
          image: ${{ steps.build-image.outputs.IMAGE_URI }}
          # The service account defined in your terraform cloudrun module will be used
          # service_account_name: ... 
